apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd

  name: argocd-role
rules:
- apiGroups: [""]
  resources: ["deployments", "services", "pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
